### ISSUE TITLE
Update .gitignore 

### ISSUE THREAD

**Issue by karthikrk1** [karthikrk1/BigDataProjects#4]
.gitignore should be updated with both Python and Java related values to have a clean repo. This also means all the IDE related stuff must be 'git rm'ed and added to .gitignore so we don't have a unclean repository.

**Comment by karthikrk1** [comment]
#6 is phase 1
Phase 2 would be a manual git remove of all the IDE related files

**Comment by karthikram1** [comment]
#6 and #7 closed. Need to remove IDE stuff

**Comment by karthikram1** [comment]
#10 should be fixing this. @karthikrk1 pls merge and close

**Comment by karthikrk1** [comment]
done
